server:
  port: 8080

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://yourIp:3306/sky_take_out?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: username
      password: password

  redis:
    host: yourIp
    port: yourPort
    password: yourPassword
    database: 0 # 操作的是0号数据库

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


sky:
  jwt:
    admin-secret: hrbust   # 设置jwt签名加密时使用的秘钥
    admin-ttl: 86400000    # 设置jwt过期时间(1天)
    user-secret: hlgrc  # 设置jwt签名加密时使用的秘钥（小程序）
    user-ttl: 36000000  # 设置jwt过期时间(600分钟)
    user-token-name: authentication  # token请求头名称
  alioss:
    accessKeyId: yourSecretId
    accessKeySecret: yourSecret
    endpoint: yourEndpoint
    bucketName: yourBackName
  wechat:
    appid: yourAppId
    secret: yourWechatSecret
  shop:
    shopAddress: 山东省威海市荣成市学院路2006号哈尔滨理工大学荣成校区
  baidu:
    ak: yourBaiduAK